### ISSUE TITLE
format the database schema so that discord-ttl is not wholly server-dependent

### ISSUE THREAD

**Issue by ayubun** [ayubun/discord-ttl#34]
this is important for future-proofing, in the event discord ever begins to support bots in user DMs 👀 perhaps just naming the current `ttl_settings` table to `server_ttl_settings` or something

**Comment by Pyker** [comment]
you could probably keep the server-based table but use something like `@me` as the server id for dms, and the dm channel id as... well, the channel id. that should make everything work together just fine

**Comment by ayubun** [comment]
well, i could, but that requires the column to be a string, which is more error prone :c @Pyker perhaps what i could do is have an in-code enum to represent this, and just assign it a negative value

**Comment by Pyker** [comment]
maybe, but keep in mind the maximum integer in sqlite is 1196994967353184296, 18446744073709551615 if it's unsigned. that's 19 and 20 chars, respectfully, and current snowflake ids are already at 19 chars, so perhaps it would be best to store them as strings regardless.

**Comment by ayubun** [comment]
hm, thats a good point :o

**Comment by ayubun** [comment]
this is being worked on in #38
